apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-mate-back-dep
spec:
  selector:
    matchLabels:
      app: cal-mate-back-kube
  replicas: 1
  template:
    metadata:
      labels:
        app: cal-mate-back-kube
    spec:
      containers:
      - name: boot-container
        image: kang92/cal_mate_back:80
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        # Spring Boot??application.yml???ï¿½ï¿½? mariadb-persistï¿??ï¿½ìŠ¤?ï¿½ë¡œ ?ï¿½ìš©?ï¿½ë„ï¿??ï¿½ì •?ï¿½ì–´ ?ï¿½ìœ¼ë¯€ï¿?
        # Kubernetes?ï¿½ì„œ???ï¿½ë¹„?ï¿½ëª…(mariadb003ser)???ï¿½ìš©?ï¿½ë„ï¿??ï¿½ê²½ë³€?ï¿½ë¡œ ?ï¿½ì •?ï¿½í•©?ï¿½ë‹¤.
        - name: SPRING-DATASOURCE-URL
          value: "jdbc:mariadb://cal-mate-mariadb-ser:3310/calcdb"
        - name: SPRING-DATASOURCE-USERNAME
          value: "cal-mate"
        - name: SPRING-DATASOURCE-PASSWORD
          value: "cal123123"

        # ?¬ê¸°ë¶€??ì¶”ê?
        volumeMounts:
        - name: backend-storage
          mountPath: /app/uploads
          subPath: uploads
        - name: backend-storage
          mountPath: /app/img
          subPath: img

        # ì»¨í…Œ?ï¿½ë„ˆê°€ ?ï¿½ë˜?ï¿½ì„ ë°›ì„ ì¤€ë¹„ï¿½? ?ï¿½ì—ˆ?ï¿½ï¿½? ?ï¿½ì¸
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        # ì»¨í…Œ?ï¿½ë„ˆê°€ ?ï¿½ìƒ?ï¿½ìœ¼ï¿??ï¿½í–‰ ì¤‘ì¸ì§€ ?ï¿½ì¸
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3

      # volumes ë¸”ë¡ ì¶”ê?
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: backend-data-pvc

